src/Entity/Civil.php
<?php

namespace App\Entity;

use App\Repository\CivilRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CivilRepository::class)]
class Civil
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column]
    private ?int $idUnique = null;

    #[ORM\Column(nullable: true)]
    private ?int $age = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telNumber = null;

    #[ORM\OneToMany(mappedBy: 'civil', targetEntity: Pictures::class, cascade: ['persist'],orphanRemoval: true)]
    private Collection $documents;

    #[ORM\OneToMany(mappedBy: 'suspect', targetEntity: Arrestation::class, cascade: ['persist'],orphanRemoval: true)]
    private Collection $arrestations;

    #[ORM\ManyToOne(inversedBy: 'civils')]
    private ?Ethnie $type = null;

    #[ORM\ManyToOne(inversedBy: 'civils')]
    private ?Gender $gender = null;

    #[ORM\Column(nullable: true)]
    private ?bool $PPA = null;

    #[ORM\Column(nullable: true)]
    private ?bool $driveCard = null;

    #[ORM\OneToOne(mappedBy: 'suspect', cascade: ['persist', 'remove'])]
    private ?JudiciaryCase $judiciaryCase = null;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
        $this->arrestations = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getIdUnique(): ?int
    {
        return $this->idUnique;
    }

    public function setIdUnique(int $idUnique): self
    {
        $this->idUnique = $idUnique;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(?int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getTelNumber(): ?string
    {
        return $this->telNumber;
    }

    public function setTelNumber(?string $telNumber): self
    {
        $this->telNumber = $telNumber;

        return $this;
    }

    /**
     * @return Collection<int, Pictures>
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Pictures $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents->add($document);
            $document->setCivil($this);
        }

        return $this;
    }

    public function removeDocument(Pictures $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getCivil() === $this) {
                $document->setCivil(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Arrestation>
     */
    public function getArrestations(): Collection
    {
        return $this->arrestations;
    }

    public function addArrestation(Arrestation $arrestation): self
    {
        if (!$this->arrestations->contains($arrestation)) {
            $this->arrestations->add($arrestation);
            $arrestation->setSuspect($this);
        }

        return $this;
    }

    public function removeArrestation(Arrestation $arrestation): self
    {
        if ($this->arrestations->removeElement($arrestation)) {
            // set the owning side to null (unless already changed)
            if ($arrestation->getSuspect() === $this) {
                $arrestation->setSuspect(null);
            }
        }
        return $this;
    }

    public function getTotalArrestations()
    {
        $totalArrestation = count($this->getArrestations());
        return $totalArrestation;
    }

    public function getType(): ?Ethnie
    {
        return $this->type;
    }

    public function setType(?Ethnie $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function fixPicture()
    {
        $da = [];
        foreach($this->getDocuments() as $d)
        {
            $da[]= $d;
        }
        if(empty($da))
        {
            $da = null;
        } else {
            return $da;
        }
        return $da;
    }

    public function isPPA(): ?bool
    {
        return $this->PPA;
    }

    public function setPPA(?bool $PPA): self
    {
        $this->PPA = $PPA;

        return $this;
    }

    public function isDriveCard(): ?bool
    {
        return $this->driveCard;
    }

    public function setDriveCard(?bool $driveCard): self
    {
        $this->driveCard = $driveCard;

        return $this;
    }

    public function checkPPA()
    {
        if($this->isPPA())
        {
            return 'Valide';
        } else {
            return 'Invalide';
        }
    }

    public function checkDriveCard()
    {
        if($this->isDriveCard())
        {
            return 'Valide';
        } else {
            return 'Invalide';
        }
    }

    public function getJudiciaryCase(): ?JudiciaryCase
    {
        return $this->judiciaryCase;
    }

    public function setJudiciaryCase(?JudiciaryCase $judiciaryCase): self
    {
        // unset the owning side of the relation if necessary
        if ($judiciaryCase === null && $this->judiciaryCase !== null) {
            $this->judiciaryCase->setSuspect(null);
        }

        // set the owning side of the relation if necessary
        if ($judiciaryCase !== null && $judiciaryCase->getSuspect() !== $this) {
            $judiciaryCase->setSuspect($this);
        }

        $this->judiciaryCase = $judiciaryCase;

        return $this;
    }

    public function getAllMoneySentence()
    {
        $money = null;
        foreach($this->getArrestations() as $a)
            {
                $money += $a->getAllMoneySentences();
            }
        $inputString = $money;
        $pattern = '/(?<=\d)(?=(\d{3})+(?!\d))/';
        $replacement = ' ';
        $outputString = preg_replace($pattern, $replacement, $inputString);

        return $outputString;
    }
}

src/Entity/JudiciaryCase.php
<?php

namespace App\Entity;

use App\Repository\JudiciaryCaseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JudiciaryCaseRepository::class)]
class JudiciaryCase
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\OneToMany(mappedBy: 'judiciaryCase', targetEntity: Arrestation::class)]
    private Collection $arrestations;


    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $decision = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'judiciaryCases')]
    private Collection $magistrate;

    #[ORM\OneToOne(inversedBy: 'judiciaryCase', cascade: ['persist', 'remove'])]
    private ?Civil $suspect = null;

    public function __construct()
    {
        $this->arrestations = new ArrayCollection();
        $this->magistrate = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection<int, Arrestation>
     */
    public function getArrestations(): Collection
    {
        return $this->arrestations;
    }

    public function addArrestation(Arrestation $arrestation): self
    {
        if (!$this->arrestations->contains($arrestation)) {
            $this->arrestations->add($arrestation);
            $arrestation->setJudiciaryCase($this);
        }

        return $this;
    }

    public function removeArrestation(Arrestation $arrestation): self
    {
        if ($this->arrestations->removeElement($arrestation)) {
            // set the owning side to null (unless already changed)
            if ($arrestation->getJudiciaryCase() === $this) {
                $arrestation->setJudiciaryCase(null);
            }
        }

        return $this;
    }

    public function getDecision(): ?string
    {
        return $this->decision;
    }

    public function setDecision(?string $decision): self
    {
        $this->decision = $decision;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getMagistrate(): Collection
    {
        return $this->magistrate;
    }

    public function addMagistrate(User $magistrate): self
    {
        if (!$this->magistrate->contains($magistrate)) {
            $this->magistrate->add($magistrate);
        }

        return $this;
    }

    public function removeMagistrate(User $magistrate): self
    {
        $this->magistrate->removeElement($magistrate);

        return $this;
    }

    public function getSuspect(): ?Civil
    {
        return $this->suspect;
    }

    public function setSuspect(?Civil $suspect): self
    {
        $this->suspect = $suspect;

        return $this;
    }
}

src/Form/JudiciaryCaseType.php
<?php

namespace App\Form;

use App\Entity\Arrestation;
use App\Entity\Civil;
use App\Entity\JudiciaryCase;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JudiciaryCaseType extends AbstractType
{
    
    private EntityManagerInterface $em;

    /**
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }


    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateTimeType::class,[
                'label' => 'Date de la demande :',
                'data' => new \DateTime('now'),

            ])
            ->add('decision', TextareaType::class, [
                'label' => 'Décision de Justice :'
            ])
            ->add('suspect', EntityType::class, [
                'class' => Civil::class,
                'label' => 'Identitié du suspect :',
                'autocomplete' => true
            ])
            ->add('arrestations', EntityType::class,[
                'class' => Arrestation::class,
                'label' => 'Arrestations',
                'multiple' => true,
                'autocomplete' => true
            ])
            ->add('magistrate', EntityType::class, [
                'class' => User::class,
                'multiple' => true,
                'label' => 'Magistrats :',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->join('u.rank', 'r')
                        ->where('r.name IN (:ranks)')
                        ->setParameter('ranks', ['Juge', 'Procureur', 'Avocat']);
                },
                'autocomplete' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => JudiciaryCase::class,
        ]);
    }

    public function findRankByJudiciaryCase(int $judiciaryCaseId): ?string
    {
        $query = $this->createQueryBuilder('jc')
            ->select('r.rank')
            ->leftJoin('jc.magistrate', 'u')
            ->leftJoin('u.rank', 'r')
            ->where('jc.id = :judiciaryCaseId')
            ->setParameter('judiciaryCaseId', $judiciaryCaseId)
            ->setMaxResults(1);

        return $query->getQuery()->getOneOrNullResult();
    }
}

src/Controller/JudiciaryCaseController.php
<?php

namespace App\Controller;

use App\Classe\Search;
use App\Entity\JudiciaryCase;
use App\Form\JudiciaryCaseType;
use App\Form\SearchType;
use App\Repository\JudiciaryCaseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/judiciary/case')]
class JudiciaryCaseController extends AbstractController
{
    #[Route('/', name: 'app_judiciary_case_index', methods: ['GET'])]
    public function index(Request $request ,JudiciaryCaseRepository $judiciaryCaseRepository): Response
    {
        $search = new Search();
        $search->page = $request->get('page',1);
        $form = $this->createForm(SearchType::class, $search);
        $form->handleRequest($request);
        $judiciaryCases = $judiciaryCaseRepository->findWidthSearch($search);

        return $this->render('judiciary_case/index.html.twig', [
            'judiciary_cases' => $judiciaryCases,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/new', name: 'app_judiciary_case_new', methods: ['GET', 'POST'])]
    public function new(Request $request, JudiciaryCaseRepository $judiciaryCaseRepository): Response
    {
        $judiciaryCase = new JudiciaryCase();
        $form = $this->createForm(JudiciaryCaseType::class, $judiciaryCase);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $judiciaryCaseRepository->save($judiciaryCase, true);

            return $this->redirectToRoute('app_judiciary_case_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('judiciary_case/new.html.twig', [
            'judiciary_case' => $judiciaryCase,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_judiciary_case_show', methods: ['GET'])]
    public function show(JudiciaryCase $judiciaryCase): Response
    {
        return $this->render('judiciary_case/show.html.twig', [
            'judiciary_case' => $judiciaryCase,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_judiciary_case_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, JudiciaryCase $judiciaryCase, JudiciaryCaseRepository $judiciaryCaseRepository): Response
    {
        $form = $this->createForm(JudiciaryCaseType::class, $judiciaryCase);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $judiciaryCaseRepository->save($judiciaryCase, true);

            return $this->redirectToRoute('app_judiciary_case_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('judiciary_case/edit.html.twig', [
            'judiciary_case' => $judiciaryCase,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_judiciary_case_delete', methods: ['POST'])]
    public function delete(Request $request, JudiciaryCase $judiciaryCase, JudiciaryCaseRepository $judiciaryCaseRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$judiciaryCase->getId(), $request->request->get('_token'))) {
            $judiciaryCaseRepository->remove($judiciaryCase, true);
        }

        return $this->redirectToRoute('app_judiciary_case_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/judiciary_case/_delete_form.html.twig
<form method="post" action="{{ path('app_judiciary_case_delete', {'id': judiciary_case.id}) }}" onsubmit="return confirm('Êtes vous sûr de vouloir supprimer ce casier judiciaire ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ judiciary_case.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/judiciary_case/_form.html.twig
<div class="container text-light mt-4">
    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-4">
            {{ form_row(form.date) }}
        </div>
        <div class="col-md-4">
            {{ form_row(form.suspect) }}
        </div>
        <div class="col-md-4">
            {{ form_row(form.magistrate) }}
        </div>
    </div>
    <div class="row"></div>
    {{ form_row(form.arrestations) }}
    <div class="row">
        {{ form_row(form.decision) }}
    </div>
    <div class="d-flex justify-content-end">
        <button class="btn btn-success">{{ button_label|default('Valider') }}</button>
    </div>
    {{ form_end(form) }}
</div>

templates/judiciary_case/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier{% endblock %}

{% block content %}
    {% if is_granted('ROLE_LSPD') %}
    <h1 class="text-center mt-4">Modifier casier judiciaire de : {{ judiciary_case.suspect.firstname }} {{ judiciary_case.suspect.lastname }}</h1>

<hr>
    {{ include('judiciary_case/_form.html.twig', {'button_label': 'Valider'}) }}
<hr>
    <div class="container d-flex justify-content-between">
        <a href="{{ path('app_judiciary_case_index') }}"><button class="btn btn-warning">Retour à la liste</button></a>
        {{ include('judiciary_case/_delete_form.html.twig') }}
    </div>
    {% else %}
        <h1 class="text-center mt-5">404 ERROR NOT FOUND</h1>
        <p class="text-center mt-5">Vous ne disposez pas des droits nécessaires</p>
    {% endif %}
{% endblock %}

templates/judiciary_case/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}JudiciaryCase index{% endblock %}

{% block content %}
    <h1 class="text-center mt-4">Liste des casiers judiciaire</h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h4 class="fs-5">Rechercher par nom :</h4>
            <form>
                {{ form_row(form.string) }}
                {{ form_widget(form.filtrer) }}
            </form>
        </div>
        <div class="col-md-9">
            <table class="table text-light">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Suspect</th>
                    <th>Décision</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for judiciary_case in judiciary_cases %}
                    <tr>
                        <td>{{ judiciary_case.date ? judiciary_case.date|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ judiciary_case.suspect.firstname }} {{ judiciary_case.suspect.lastname }}</td>
                        <td>{{ judiciary_case.decision }}</td>
                        <td>
                            <a href="{{ path('app_judiciary_case_show', {'id': judiciary_case.id}) }}" class="text-decoration-none">&#128065;&#65039;</a>
                            {% if is_granted('ROLE_LSPD') %}
                            <a href="{{ path('app_judiciary_case_edit', {'id': judiciary_case.id}) }}" class="text-decoration-none">&#9997;</a>
                            <form method="post" action="{{ path('app_judiciary_case_delete', {'id': judiciary_case.id}) }}" onsubmit="return confirm('Êtes vous sûr de vouloir supprimer ce casier judiciaire ?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ judiciary_case.id) }}">
                            <button class="btn btn-link text-decoration-none">&#128465;&#65039;</button>
                            </form>
                            {% endif %}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4" class="text-center">Aucun casier enregistré</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="d-flex justify-content-center">
                {{ knp_pagination_render(judiciary_cases) }}
            </div>
        </div>

    </div>
    {% if is_granted('ROLE_LSPD') %}
<div class="d-flex justify-content-end">
    <a href="{{ path('app_judiciary_case_new') }}"><button class="btn btn-warning">Créer un nouveau casier</button></a>
</div>
    {% endif %}
</div>

{% endblock %}

templates/judiciary_case/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un casier judiciaire{% endblock %}

{% block content %}
    <h1 class="text-center mt-4">Créer un casier judiciaire</h1>

    {{ include('judiciary_case/_form.html.twig') }}

    <a href="{{ path('app_judiciary_case_index') }}">
        <button class="btn btn-info">Retour à la liste</button>
    </a>
{% endblock %}

templates/judiciary_case/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Casier judiciaire{% endblock %}

{% block content %}
    <h1 class="text-center mt-4">Casier judiciaire de : {{ judiciary_case.suspect.firstname }} {{ judiciary_case.suspect.lastname }}</h1>

    <div class="container ">
        <div class="row">
            <div class="col-md-6 mt-5">
                <div class="card" style="width: 18rem;">
                    {% if judiciary_case.suspect.fixPicture is null %}
                        <p class="text-center mt-2">Veuillez ajouter des documents : <a href="{{ path('app_civil_edit', {'id': judiciary_case.suspect.id}) }}">ici</a></p>
                        <hr>
                    {% else %}
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <div class="carousel-indicators">
                                {% for iteration in 1..judiciary_case.suspect.fixPicture|length %}
                                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ iteration - 1 }}" {{ (loop.first ) ?'class="active" aria-current="true"' : '' }} aria-label="Slide {{ iteration }}"></button>
                                {% endfor %}
                            </div>
                            <div class="carousel-inner">
                                {% for img in judiciary_case.suspect.fixPicture %}
                                    <div class="carousel-item {{ (loop.first) ? 'active' : ''}}">
                                        <img class="d-block w-100" src="{{ asset('assets/uploads/documents/mini/300x300-') ~ img.filename }}" alt="{{ img.filename }}">
                                    </div>
                                {% endfor %}
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Précédent</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Suivant</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">Informations Personnelles :</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><b>Date du casier :</b> {{ judiciary_case.date|date('d/m/Y H:m') }}</li>
                        <li class="list-group-item"><b>ID Unique :</b> {{ judiciary_case.suspect.idUnique }}</li>
                        <li class="list-group-item"><b>Nom :</b> {{ judiciary_case.suspect.lastname }}</li>
                        <li class="list-group-item"><b>Prénom :</b> {{ judiciary_case.suspect.firstname }}</li>
                        <li class="list-group-item"><b>Âge :</b> {{ judiciary_case.suspect.age }}</li>
                        <li class="list-group-item"><b>Sexe :</b> {{ judiciary_case.suspect.gender }}</li>
                        <li class="list-group-item"><b>Type :</b> {{ judiciary_case.suspect.type }}</li>
                        <li class="list-group-item"><b>Permis de conduire :</b> {{ judiciary_case.suspect.checkDriveCard }}</li>
                        <li class="list-group-item"><b>PPA :</b> {{ judiciary_case.suspect.checkPPA }}</li>
                    </ul>
                    <div class="card-body d-flex justify-content-center">
                        <a href="{{ path('app_civil_show', {'id': judiciary_case.suspect.id}) }}" class="card-link"><button class="btn btn-primary">Fiche du Civil</button></a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mt-5">
                <div class="card" style="width: 18rem;">
                    <img src="{{ asset('assets/img/doj.jpeg') }}" class="card-img-top img-fluid" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Décisions de Justice :</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <b>Magistrats :</b>
                                {% for m in judiciary_case.magistrate %}
                                    <br>
                                - {{ m.rank }} {{ m.firstname }} {{ m.lastname }}
                                {% endfor %}
                            </li>
                        <li class="list-group-item">
                            <b>Total d'amendes à ce jour :</b> <br>   {{ judiciary_case.suspect.allMoneySentence }} $
                        </li>
                    </ul>
                    <div class="card-body">
                        <p class="card-text"><b>Verdict :</b>
                            <br>
                            {{ judiciary_case.decision }}</p>
                    </div>
                </div>
        </div>
            <h5 class="text-center mt-5">Listes des Arrestations de {{ judiciary_case.suspect.firstname }} {{ judiciary_case.suspect.lastname }}</h5>
            <table class="table table-hover bg-light mt-3 rounded">
                <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Agent présents</th>
                    <th scope="col">Nombres de faits</th>
                    <th scope="col">Amendes</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for a in judiciary_case.suspect.arrestations %}
                <tr>
                    <th scope="row">{{ a.date|date('d/m/Y à H:m') }}</th>
                    <td>
                        {% for agent in a.agent %}
                            [{{ agent.matricule }}]
                        {% endfor %}
                    </td>
                    <td>{{ a.countTotalSentence }}</td>
                    <td>{{ a.getAllMoneySentences }} $</td>
                    <td>
                        <a href="{{ path('app_arrestation_show', {'id': a.id}) }}" class="text-decoration-none">&#128065;&#65039;</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        <div class="d-flex justify-content-between mt-5">
            <a href="{{ path('app_judiciary_case_index') }}">
                <button class="btn btn-warning">Retour à la liste</button>
            </a>
            {% if is_granted('ROLE_LSPD') %}
            {{ include('judiciary_case/_delete_form.html.twig') }}
            <a href="{{ path('app_judiciary_case_edit', {'id': judiciary_case.id}) }}">
                <button class="btn btn-success">
                    Modifier
                </button>
            </a>
            {% endif %}
        </div>
    </div>
    </div>
{% endblock %}